### ISSUE TITLE
GridLayout over populated

### ISSUE THREAD

**Issue by bigretromike** [romanvm/pyxbmct.demo#1]
Hey,

Being using pyxbmct, the window is `BlackFullWindow` with grid 20 x 20;
While adding control I add them to list and I can easly add more than 20 colums, but all added controls are not visible. Is there a way to make effect that would move right if I want to see those over 20 columns ? or should I just add ne BlackFullWindow and move bettween them (if its possible)? because there is no way to redraw already drawn window right - so I could replace controls from columns 1-20 to 21-40.
Im looking for something like paging.

**Comment by romanvm** [comment]
Please post general questions at the Kodi forum: https://forum.kodi.tv/showthread.php?tid=174859
