### ISSUE TITLE
error while running on Kodi 19

### ISSUE THREAD

**Issue by FalconEagleTest** [romanvm/pyxbmct.demo#3]
i tried to run it on kodi 19 and this is the error:

EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'TypeError'>
Error Contents: 'focusTexture' is an invalid keyword argument for this function
Traceback (most recent call last):
File "D:\kodi19\portable_data\addons\script.pyxbmct.demo\default.py", line 177, in
window = MyAddon('PyXBMCt Demo')
File "D:\kodi19\portable_data\addons\script.pyxbmct.demo\default.py", line 24, in init
self.set_active_controls()
File "D:\kodi19\portable_data\addons\script.pyxbmct.demo\default.py", line 70, in set_active_controls
self.radiobutton = pyxbmct.RadioButton('Off')
File "D:\kodi19\portable_data\addons\script.module.pyxbmct\lib\pyxbmct\addonwindow.py", line 300, in new
return super(RadioButton, cls).new(cls, -10, -10, 1, 1, *args, **kwargs)
TypeError: 'focusTexture' is an invalid keyword argument for this function
what am i doing wrong?
thanks for your help

**Comment by FalconEagleTest** [comment]
I found the issue or at list one of them, it seems something's was removed in Kodi 19,
"Changed Method parameters - Removed

ControlEdit - removed isPassword
ControlRadioButton - removed focusTexture, noFocusTexture"
https://forum.kodi.tv/showthread.php?tid=344263
So it's not just adjusting to python 3 I guess.

**Comment by romanvm** [comment]
Thank you for reporting this. I'm moving this to the parent PyXBMCt project: https://github.com/romanvm/script.module.pyxbmct/issues/16
